<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="nosql" nsURI="http://nosql/1.0" nsPrefix="nosql">
  <eClassifiers xsi:type="ecore:EClass" name="KeySpace">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="idexes" upperBound="-1"
        eType="#//Index" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="families" lowerBound="1"
        upperBound="-1" eType="#//ColumnFamily" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//Options"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1"
        eType="#//Options" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasPK" upperBound="-1"
        eType="#//PK" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Index">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="applyTo" eType="#//Column"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColumnFamily">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" lowerBound="1"
        upperBound="-1" eType="#//Column" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1"
        eType="#//Options" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PK" eType="#//PK" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" upperBound="-1" eType="#//Row"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyspace" lowerBound="1"
        eType="#//KeySpace" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Options">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Column">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datatype" lowerBound="1"
        eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnFamily" eType="#//ColumnFamily"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eLiterals name="ascii" literal="ascii"/>
    <eLiterals name="blob" value="2"/>
    <eLiterals name="boolean" value="3"/>
    <eLiterals name="counter" value="4"/>
    <eLiterals name="decimal" value="5"/>
    <eLiterals name="double" value="6"/>
    <eLiterals name="float" value="7"/>
    <eLiterals name="int" value="9"/>
    <eLiterals name="text" value="10"/>
    <eLiterals name="timestamp" value="11"/>
    <eLiterals name="uuid" value="12"/>
    <eLiterals name="timeuuid" value="16"/>
    <eLiterals name="varchar" value="13"/>
    <eLiterals name="varint" value="14"/>
    <eLiterals name="bigint" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PK">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//Column"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Row" eSuperTypes="#//ColumnFamily">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" lowerBound="1" upperBound="-1"
        eType="#//Cell" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalColumns" lowerBound="1"
        upperBound="-1" eType="#//Column" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cell">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="column" lowerBound="1"
        eType="#//Column"/>
  </eClassifiers>
</ecore:EPackage>
